server:
  port: 2222

spring:
  application:
    name: service-user

eureka:
  client:
    serviceUrl:
      #      defaultZoen: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZoen: http://localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
