server:
  port: 8080

spring:
  application:
    name: service-ribbon

eureka:
  client:
    serviceUrl:
      #      defaultZoen: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZoen: http://localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
